[workspace]
members = ["libcrux-provider", "demo-server"]

resolver = "2"

[workspace.dependencies]
rustls-libcrux-provider = { path = "libcrux-provider" }

[profile.bench]
codegen-units = 1
lto = true
